---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install Church packages
  package:
    name: 
      - ripgrep
      - volumeicon-alsa
      - arandr
      - autorandr
      - qpwgraph
      - pavucontrol
      - obs-studio
      - libghc-xmonad-contrib-dev
      - libghc-xmonad-dev
      - haskell-stack
      - xmonad
      - dmenu
      - xmobar
      - trayer
    state: present
  become: true

- name: Install TouchOSC
  ansible.builtin.apt:
    deb: https://hexler.net/pub/touchosc/touchosc-1.3.4.209-linux-arm64.deb
