---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Create the `aur_builder` user
  become: yes
  ansible.builtin.user:
    name: aur_builder
    create_home: yes
    group: wheel

- name: Allow the `aur_builder` user to run `sudo pacman` without a password
  become: yes
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    mode: 0644
    validate: 'visudo -cf %s'
- name: Update cache, the equivalent of "pacman -Sy"
  community.general.pacman:
    update_cache: true

- name: Install paru
  kewlfft.aur.aur:
    name: 
      - paru
    state: present
  become: yes
  become_user: aur_builder

- name: Clone Dotfiles
  ansible.builtin.git:
    repo: https://github.com/rickprice/dotfiles.git
    dest: /home/{{remote_regular_user}}/.dotfiles
