- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    brother_nodename: "BRWD85DE244E1EB"

- name: Install shell packages
  community.general.pacman:
    name:
      - fish
      - fisher-git
      - fzf-git
      - zoxide-git
      - starship
    executable: paru
    state: present

- name: Configure fzf
  ansible.builtin.shell: |
    fisher install "PatrickF1/fzf.fish"
  args:
    executable: /usr/bin/fish

- name: Configure fisher-ssh-agent
  ansible.builtin.shell: |
    fisher install "danhper/fish-ssh-agent"
  args:
    executable: /usr/bin/fish

- name: Configure HomeRepotTools
  ansible.builtin.shell: |
    fisher install "rickprice/HomeRepotTools_fish"
  args:
    executable: /usr/bin/fish
