---
- name: Install video packages
  kewlfft.aur.aur:
    name: 
      # Video
      - vlc
      - flowblade
      # OpenCL
      - intel-opencl-sdk
      - intel-compute-runtime
      - dmidecode
      - clinfo
    state: present
  become: true
  become_user: aur_builder

