---
# - name: Remove vim because of conflicts with Neovim-symlinks
#   community.general.pacman:
#     name: 
#       - vim
#     state: absent
#
- name: Install Neovim packages
  package:
    name: 
      - neovim
      # - neovim-symlinks
      - xclip
      # - nodejs
      # - npm
      # - python-lsp-server
    state: present
  become: true
