- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Add the user '{{ remote_regular_user }}' to the lp group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: lp
    append: yes

- name: Install cups packages and setup
  community.general.pacman:
    name: 
      - cups
      - system-config-printer
    executable: paru
    state: present

- name: Enable cups service
  ansible.builtin.systemd:
    name: cups
    state: started
    enabled: true

- name: Install Epson packages
  kewlfft.aur.aur:
    name: 
      # Epson packages
      - epson-inkjet-printer-escpr
      - epsonscan2
      # Presumably used by the installer
      - patch
      # Turbuprint improves colour accuracy
      - turboprint
    state: present
  become: true
  become_user: aur_builder
