- name: Install main packages
  community.general.pacman:
    name: 
      # Geolocating
      - perl-image-exiftool
      - gpsbabel
      - python-ijson
      # Photograpic processing
      - darktable-git
      - gimp
      - nomacs
      - imagemagick
      - openexr
      - dcraw
      - gnuplot
      - hugin
      - gphoto2
    # Collages
      - photocollage
    # Drawing
      - inkscape
    # File Manager Stuff
      - pcmanfm
      - tumbler
      - poppler-glib
      - ffmpegthumbnailer
      - freetype2
      - libgsf
      - raw-thumbnailer
      - ufraw-thumbnailer
    executable: paru
    state: present
