---
# - name: Remove xautolock because it causes annoying locking
#   community.general.pacman:
#     name: 
#       - xautolock
#     state: absent

- name: Install main packages
  kewlfft.aur.aur:
    name: 
      - luarocks
      - wezterm
      - tmux
      - alacritty
      - git-delta
      - perl
      - perl-local-lib
      - perl-archive-zip
      - cpanminus
      - lazygit
      - xorg-xinput
      - solaar
      - xpub
      - github-cli
      - difftastic
      - less
      - bat
      # Libreoffice
      - libreoffice-still
      - hunspell
      - hunspell-en_us
      - aspell

      - calibre
      - hub
      - fd
      - ripgrep
      - dotter-rs
      - reflector
      - trash-cli
      - meld
      - arandr
      - tree
      - libxml2
      - man
      - ansifilter
      - klogg-bin
      # For hardware video acceleration
      - libva-utils
      - intel-media-driver
      - linux-firmware
      # Incredibly useful command line REST utility
      - httpie
    # PKGBUILD Stuff
      - pigz
      - pbzip2
      - lbzip2
      - plzip
      - pacman-contrib
    # JSON
      - jq
    # general
      - figlet
      - keepassxc
    # Eric Bad videos
      - xdotool
    # For X11 Forwarding
      - xorg-xauth
    # Font viewer
      - gnome-font-viewer
    # PDF viewer
      - atril
    # Calendar Libraries for Python
      - python-recurring-ical-events
    # Control EWMH compliant window manager
      - wmctrl
    # Python packages that I use for personal Stuff
      - python-qrcode
      - python-zxing-cpp
      - zbar
      # This one seems to be better at grabbing the QR code from photographs
      - qrtool
      # This is so Arch knows what packages I use
      - pkgstats
      # This is to convert SVG to png (particularly for PricePixelDesignHouse)
      - resvg
      # OCR Software, bringing in the data should bring in the main executable as well
      - tesseract-data-eng
      # Software to display images in the terminal
      - timg
      # Terminal browser
      - elinks
      # For PDF in Mutt
      - zathura
      # Add urlscan for mutt to show links in browser
      - urlscan
      # To do automatic updates with Ansible
      - yay
      # Need DNS utilities sometimes
      - bind
      # Allow numlock to start in the on state
      # https://wiki.archlinux.org/title/Activating_numlock_on_bootup#Early_bootup_(mkinitcpio)
      - mkinitcpio-numlock
      # Broot is a good way to find things on the FS
      - broot
      # Atuin shell history manager
      - atuin
      # Needed by atuin for Bash shell
      - blesh
      # zoxide to manage cd 
      - zoxide
      # To connect remotely
      - tailscale
      # To run with Claude
      - claude-code
      # For Tamara backgrounds
      - rust-name-time-period
      - rust-images-matching-subdirectories
      # This is a better SSH key password deaemon
      - keychain
    state: present
  become: true
  become_user: aur_builder

- name: Run reflector service
  ansible.builtin.systemd:
    name: reflector
    state: started
    # enabled: true

- name: Enable reflector.timer service
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: true
