---
- name: Remove xautolock because it causes annoying locking
  community.general.pacman:
    name: 
      - xautolock
    state: absent

- name: Install main packages
  kewlfft.aur.aur:
    name: 
      - wezterm
      - alacritty
      - git-delta
      - perl
      - perl-local-lib
      - perl-archive-zip
      - cpanminus
      - lazygit
      - xorg-xinput
      - solaar
      - xpub
      - github-cli
      - difftastic
      - less
      - bat
      - libreoffice-fresh
      - calibre
      - hub
      - fd
      - ripgrep
      - dotter-rs
      - reflector
      - trash-cli
      - meld
      - arandr
      - tree
      # For hardware video acceleration
      - libva-utils
      - intel-media-driver
      - linux-firmware
      # Incredibly useful command line REST utility
      - httpie
    state: present
  become: yes
  become_user: aur_builder

- name: Run reflector service
  ansible.builtin.systemd:
    name: reflector
    state: started
    # enabled: true

- name: Enable reflector.timer service
  ansible.builtin.systemd:
    name: reflector.timer
    state: started
    enabled: true
