---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install Church packages
  kewlfft.aur.aur:
    name: 
      - qpwgraph
      - obs-studio
      - openlp
      - python-vlc
      - touchosc-bin
      - python-pipenv
      - python-openlp-osc-control
    state: present
  become: true
  become_user: aur_builder

- name: Enable and start OpenLPOSCControl service
  ansible.builtin.systemd:
    name: OpenLPOSCControl@church
    state: started
    enabled: true
