---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install Church packages
  kewlfft.aur.aur:
    name: 
      - qpwgraph
      - obs-studio
      - openlp
    # Hexler
    state: present
  become: true
