---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install window manager packages
  package:
    name: 
      - i3
      - i3status
      - udiskie
      - pcmanfm
      - alacritty
      - curl
      # stuff to make a desktop work
      - feh
      - gnome-system-monitor
      - bemenu
      # - volumeicon
      - xfce4-power-manager
    state: present
  become: true

- name: Create external_repo directory
  ansible.builtin.file:
    path: /home/{{remote_regular_user}}/Documents/external_repo
    state: directory
    mode: '0755'
