---

# EB Garamond font

# https://github.com/georgd/EB-Garamond

# The Ubuntu repos already contain the latest release of EB Garamond
# taha@luxor:~
# $ apt-cache madison fonts-ebgaramond
# fonts-ebgaramond |    0.016-1 | http://se.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

# Not exactly sure on the recommended usage with *LaTeX, but fontspec and LuaLaTeX should be a good bet.
# See some examples in https://github.com/georgd/EB-Garamond/tree/master/tests

- name: Install EB Garamond from Ubuntu repos
  ansible.builtin.apt:
    name: fonts-ebgaramond
    state: present
  register: ebgaramond_installed

- name: Update the font cache
  ansible.builtin.command: fc-cache -fv
  when: ebgaramond_installed.changed | bool
