---
- name: Install font packages
  package:
    name: 
      # - xorg-xfontsel
      - iosevka-fonts
      - iosevka-term-fonts
      - ttf-iosevka-nerd
      - noto-fonts
      - noto-fonts-emoji
      - noto-fonts-extra
      - ttf-noto-nerd
      - ttf-linux-libertine
      - powerline-fonts
      - adobe-source-code-pro-fonts
      - ttf-font-awesome
      - ttf-vista-fonts
      - ebgaramond-otf
      - amazon-fonts
    state: present
  become: true

