---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install Snapd
  package:
    name: 
      - snapd
    state: present

- name: Clone Dotfiles
  ansible.builtin.git:
    repo: https://github.com/rickprice/dotfiles.git
    dest: /home/{{remote_regular_user}}/.dotfiles
