---
- name: Install video packages
  kewlfft.aur.aur:
    name: 
      # Video
      - vlc
      - flowblade
      # OpenCL
      - intel-opencl-sdk
      - intel-compute-runtime
      - dmidecode
      - clinfo
      - gst-libav
      - gst-plugins-base
      - gst-plugins-good
      - gst-plugins-bad
      - gst-plugins-ugly
      - ffmpeg
    state: present
  become: true
  become_user: aur_builder

