---
- hosts: 127.0.0.1
  connection: local
  become: true
  roles:
    - { role: ihmels.rpmfusion_repo }  
    - initial_setup
    - main_packages
    # - audio
    # - video
    - bluetooth
    - browsers
    - filesystems
    - fonts
    - neovim
    # - power
    - shell
    - ssh
    - window_manager
    - final_setup
