- name: Install 1Password
  kewlfft.aur.aur:
    name: 
      - 1password
      # Fix state tool libxcrypt problems
      - libxcrypt-compat
      - python-isort
      - python2
      # Needed for testing Django
      - enchant
    # For handling CVE fixups
      - gitkraken
    state: present
  become: yes
  become_user: aur_builder
