---
- name: Remove fonts so install can go through
  ansible.builtin.package:
    name:
    - ttf-carlito

    state: absent
  become: true
  become_user: aur_builder

- name: Install Fonts
  kewlfft.aur.aur:
    name:
    # ttf-chromeos-fonts
    # ttf-clear-sans
    # ttf-gentium
    # ttf-noto
    - adobe-source-code-pro-fonts
    - adobe-source-sans-pro-fonts
    - adobe-source-serif-pro-fonts
    - amazon-fonts
    - artwiz-fonts
    - ebgaramond-otf
    - font-bh-ttf
    - gsfonts
    - libertinus-font
    - noto-fonts
    - noto-fonts-emoji
    - noto-fonts-extra
    - otf-fira-mono
    - otf-fira-sans
    - otf-overpass
    - powerline-fonts
    - tex-gyre-fonts
    - gnu-free-fonts
    - ttf-bitstream-vera
    - ttf-bitstream-vera
    - ttf-caladea
    # - ttf-carlito
    # - ttf-courier-prime-emoji
    - ttf-dejavu
    - ttf-dejavu
    - ttf-freefont
    - ttf-fira-sans
    - ttf-font-awesome
    - ttf-gelasio-ib
    - ttf-google-fonts-git
    - ttf-impallari-cantora
    - ttf-inconsolata
    - ttf-inconsolata
    - ttf-iosevka
    - ttf-iosevka-nerd
    - ttf-junicode
    - ttf-liberation
    - ttf-linux-libertine
    - ttf-linux-libertine
    - ttf-merriweather
    - ttf-monaco
    - ttf-ms-fonts
    - ttf-ms-fonts
    - ttf-noto-nerd
    - ttf-opensans
    - ttf-roboto
    - ttf-signika
    - ttf-source-sans-pro-ibx
    - ttf-symbola
    - ttf-ubuntu-font-family
    - ttf-ubuntu-font-family
    - ttf-vista-fonts
    - ttf-vista-fonts
    - xorg-xfontsel
    # For Postscript 3 fonts
    - phostpdl 

    state: present
  become: true
  become_user: aur_builder

- name: Sub Pixel RGB Hints
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/10-sub-pixel-rgb.conf
    dest: /etc/fonts/conf.d/10-sub-pixel-rgb.conf
    owner: root
    group: root
    state: link
  become: true

- name: Use LCD Filter on Fonts
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/11-lcdfilter-default.conf
    dest: /etc/fonts/conf.d/11-lcdfilter-default.conf
    owner: root
    group: root
    state: link
  become: true

- name: No Bitmap Fonts
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/70-no-bitmaps.conf
    dest: /etc/fonts/conf.d/70-no-bitmaps.conf
    owner: root
    group: root
    state: link
  become: true

- name: Texlive Fonts
  ansible.builtin.file:
    src: /usr/share/fontconfig/conf.avail/09-texlive-fonts.conf
    dest: /etc/fonts/conf.d/09-texlive-fonts.conf
    owner: root
    group: root
    state: link
  become: true

- name: Ensure we are using subpixel hinting
  ansible.builtin.lineinfile:
    path: /etc/profile.d/freetype2.sh
    regexp: '^export FREETYPE_PROPERTIES='
    line: 'export FREETYPE_PROPERTIES="truetype:interpreter-version=40"'
