- name: Install main packages
  community.general.pacman:
    name: 
      - wezterm-git
      - git-delta-git
      - perl
      - perl-local-lib
      - perl-archive-zip
      - cpanminus
      - lazygit
      - xorg-xinput
      - solaar
      - xpub
      - github-cli
      - difftastic
      - bat
      - libreoffice-fresh
      - calibre
      - hub
      - fd
    executable: paru
    state: present
