---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install dropbox packages
  kewlfft.aur.aur:
    name: 
      - dropbox
      - qt5-base
      - python-gpgme
      - snixembed-git
    state: present
  become: yes
  become_user: aur_builder

- name: From the Arch Wiki Prevent Automatic updates which always go wrong...
  ansible.builtin.shell: |
    rm -rf ~/.dropbox-dist &&
    install -dm0 ~/.dropbox-dist
  become: yes
  become_user: '{{ remote_regular_user }}'
