- name: Install vpn packages
  kewlfft.aur.aur:
    name: 
      - wireguard-tools
      - openresolv
      - wireguard-dkms
      - networkmanager-openvpn
    state: present
  become: yes
  become_user: aur_builder

