---
- name: Install main packages
  package:
    name: 
      - wezterm-git
      - alacritty
      - git-delta-git
      # - perl
      # - perl-local-lib
      # - perl-archive-zip
      # - cpanminus
      - lazygit
      - xorg-xinput
      # - solaar
      # - xpub
      - github-cli
      - difftastic
      - bat
      - libreoffice-fresh
      - calibre
      - hub
      - fd
      - dotter-rs
    state: present
  become: true
