---
- name: Install main packages
  package:
    name: 
      - wezterm
      - alacritty
      - git-delta
      # - perl
      # - perl-local-lib
      # - perl-archive-zip
      # - cpanminus
      # - lazygit
      # - xorg-xinput
      # - solaar
      # - xpub
      # - github-cli
      - difftastic
      - bat
      - libreoffice-fresh
      - calibre
      - hub
      # - fd
      # - dotter-rs
      - rust
    state: present
  become: true
