---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install main packages
  package:
    name: 
      - alacritty
      # - git-delta
      # - perl
      # - perl-local-lib
      # - perl-archive-zip
      # - cpanminus
      - xinput
      - solaar
      # - xpub
      - gh
      - bat
      - libreoffice
      # - calibre
      # - hub
      - fd-find
      - ripgrep
      - build-essential
      - cmake
      - libfreetype6-dev
      - libfontconfig1-dev
      - xclip
    state: present
  become: true

# - name: Install Snap applications
#   snap:
#     name: 
#       - lazygit-gm
#       - difftastic
#     state: present

- name: check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  become: true
  become_user: "{{ remote_regular_user }}"

- name: Download Installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust

- name: install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  become: true
  # become_user: "{{ ansible_env.USER }}"
  become_user: {{ remote_regular_user }}
  tags:
    - rust

- name: Install Dotter
  community.general.cargo:
    name: dotter
    executable: /home/{{ remote_regular_user }}/.cargo/bin/cargo
    path: /usr/local
    state: latest
  become: true

- name: Install Wezterm
  ansible.builtin.apt:
    deb: https://github.com/wez/wezterm/releases/download/20230712-072601-f4abf8fd/wezterm-20230712-072601-f4abf8fd.Ubuntu22.04.deb
