---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install shell packages
  kewlfft.aur.aur:
    name: 
      - fish
      - fisher
      - fzf
      - zoxide
      - starship
      - zsh
      - zsh-syntax-highlighting 
      - zsh-autosuggestions
    state: present
  become: true
  become_user: aur_builder

- name: Ensure the user '{{ remote_regular_user }}' has a fish shell.
  user:
    name: "{{ remote_regular_user }}"
    shell: /usr/bin/zsh
    state: present
  become: true
  #
# - name: Ensure the user '{{ remote_regular_user }}' has a fish shell.
#   user:
#     name: "{{ remote_regular_user }}"
#     shell: /usr/bin/fish
#     state: present
#   become: true


# - name: Configure fzf
#   ansible.builtin.shell: |
#     fisher install "PatrickF1/fzf.fish"
#   args:
#     executable: /usr/bin/fish
#   become: true
#   become_user: "{{ remote_regular_user }}"
#
# - name: Configure fisher-ssh-agent
#   ansible.builtin.shell: |
#     fisher install "danhper/fish-ssh-agent"
#   args:
#     executable: /usr/bin/fish
#   become: true
#   become_user: "{{ remote_regular_user }}"

# - name: Configure HomeRepotTools
#   ansible.builtin.shell: |
#     fisher install "rickprice/HomeRepotTools_fish"
#   args:
#     executable: /usr/bin/fish
#   become: true
#   become_user: "{{ remote_regular_user }}"

#
# - name: Set PATH for Bash environment variable
# - lineinfile:
#     regexp: '^(export PATH=.*)$'
#     backrefs: yes
#     line: '\1:/home/{{ remote_regular_user}}/.local/bin'
#     path: '/{{ remote_regular_user }}/.bashrc'
#
