- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Ensure 'lp' group exists
  ansible.builtin.group:
    name: lp
    state: present

- name: Add the user '{{ remote_regular_user }}' to the lp group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: lp
    append: yes

- name: Install bluetooth packages and setup
  package:
    name: 
      - bluez
      # - bluez-utils
      # - bluez-hid2hci
      - blueman
    state: present

- name: Enable bluetooth service
  ansible.builtin.systemd:
    name: bluetooth
    state: started
    enabled: true
