- name: Remove discord because we are now using the native Arch one
  community.general.pacman:
    name: 
      - discord
    state: absent

- name: Install communication packages
  kewlfft.aur.aur:
    name: 
      - discord_arch_electron
      - slack-electron
      - zoom
    state: present
  become: yes
  become_user: aur_builder
