---
- name: Install Scribus and related packages
  kewlfft.aur.aur:
    name: 
      # Scribus
      - scribus
      - gdal
      - libvncserver
      # For managing PDF documents
      - python-pypdf
    state: present
  become: true
  become_user: aur_builder
