---
- name: Install Scribus and related packages
  kewlfft.aur.aur:
    name: 
      # Scribus
      - scribus
      - gdal
      - libvncserver
    state: present
  become: true
  become_user: aur_builder
