---
- name: Install haskell packages
  kewlfft.aur.aur:
    name: 
      - ghcup-hs-bin
      # Haskell source code formatter
      - haskell-fourmolu
    state: present
  become: yes
  become_user: aur_builder
