---
- name: Install haskell packages
  kewlfft.aur.aur:
    name: 
      - ghcup-hs-bin
      # Haskell source code formatter
      - haskell-fourmolu
      # Needed for HLS in Neovim
      - ghcide
      - haskell-language-server
    state: present
  become: yes
  become_user: aur_builder
