---
- name: Install dropbox packages
  kewlfft.aur.aur:
    name: 
      - dropbox
      - gt5-base
      - python-gpgme
    state: present
  become: yes
  become_user: aur_builder

- name: From the Arch Wiki Prevent Automatic updates which always go wrong...
  ansible.builtin.shell: |
    rm -rf ~/.dropbox-dist &&
    install -dm0 ~/.dropbox-dist
