- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Ensure 'docker' group exists
  ansible.builtin.group:
    name: docker
    state: present

- name: Add the user '{{ remote_regular_user }}' to the docker group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: docker
    append: yes

- name: Install bluetooth packages and setup
  community.general.pacman:
    name: 
      - docker
    executable: paru
    state: present

- name: Enable docker service
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
