- name: Install ActiveState useful packages
  kewlfft.aur.aur:
    name:
      - 1password
      # Fix state tool libxcrypt problems
      - libxcrypt-compat
      - python-isort
      - python-black
      # Testing things
      - python-pipx
      # - python-tox
      # - pyenv
      # - pyenv-virtualenv
      # - python-virtualenv
      # Needed for testing Django
      - enchant
    # For handling CVE fixups
      - gitkraken
    # For current_BE_sprint command
      - python-typer
      - python-click-log
      - python-atlassian-api
      # - pipman-git
    # Python's for testing
      # - python2
      - python36
    # For PR stuff
      - kubectl
      - k9s
    # For doing XML stuff
      # - xmllib
    # Python formatter
      # - ruff # We now seem to include it in the THR
    # Bazel
      - bazelisk
    # AWS CLI
      - aws-cli
    # Wiggle allows you to patch files that otherwise fail
      - wiggle
    # ActiveState requires that our ScreenSaver lock the screen after 20 minutes
      - xscreensaver
    # crudini is very useful
      # - python-iniparse-git
      # - crudini
    # ActiveState uses the vanta agent
      # - vanta-agent
    # ActiveState wants us to use tailscale
      # - tailscale
    state: present
  become: yes
  become_user: aur_builder

# - name: Enable vanta-agent service
#   ansible.builtin.systemd:
#     name: vanta-agent
#     state: started
#     enabled: true

# - name: Enable tailscale agent service
#   ansible.builtin.systemd:
#     name: tailscaled
#     state: started
#     enabled: true
