- name: Install main packages
  community.general.pacman:
    name: 
      - neovim-nightly-bin
      - neovim-symlinks
      - xclip
      - nodejs
      - npm
    executable: paru
    state: present
