---
- name: Install Neovim packages
  kewlfft.aur.aur:
    name: 
      - neovim-nightly-bin
      - neovim-symlinks
      - xclip
      - nodejs
      - npm
    state: present
  become: true
  become_user: aur_builder
