---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"

- name: Install music packages
  kewlfft.aur.aur:
    name: 
      # Metronome
      - kmetronome
      # Synthesizer ?front end?
      - qsynth
      # Virtual MIDI keyboard
      - vmpk
      - soundfont-fluid
      - fluidplug-git
      - fluidsynth
      - pro-audio 
      - realtime-generic-setup
      # - proaudio-meta
      - soundfonts-aur-meta
      # - lv2-plugins-aur-meta
      - fluidsynth-dssi
      # MIDI Debugging
      - midisnoop-git
      # MIDI programming
      - python-jack-client
      # Reaper seems to want this
      - libgme
    state: present
  become: true
  become_user: aur_builder

- name: Add the user '{{ remote_regular_user }}' to the audio group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: audio
    append: yes

- name: Add the user '{{ remote_regular_user }}' to the realtime group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: realtime
    append: yes

- name: Link default sound font for fluidsynth
  ansible.builtin.file:
    src: /usr/share/soundfonts/FluidR3_GM.sf2
    dest: /usr/share/soundfonts/default.sf2
    owner: root
    group: root
    state: link
  become: true

