---
- name: get the non root remote user
  set_fact:
    remote_regular_user: "{{ ansible_env.SUDO_USER or ansible_user_id }}"
    printer_ip: 192.168.50.253
    printer_ip2: 192.168.50.144

- name: Add the user '{{ remote_regular_user }}' to the audio group
  ansible.builtin.user:
    name: '{{ remote_regular_user }}'
    groups: audio
    append: yes

- name: Install music packages
  kewlfft.aur.aur:
    name: 
      # Metronome
      - kmetronome
      # Synthesizer ?front end?
      - qsynth
      # Virtual MIDI keyboard
      - vmpk
      - soundfont-fluid
      - fluidplug-git
      - fluidsynth
      - pro-audio 
      - realtime-generic-setup
      - proaudio-meta
      - soundfonts-aur-meta
      - lv2-plugins-aur-meta
    state: present
  become: true
  become_user: aur_builder

