---
- name: Install music packages
  kewlfft.aur.aur:
    name: 
      # Metronome
      - kmetronome
      # Synthesizer ?front end?
      - qsynth
      # Virtual MIDI keyboard
      - vmpk
      - soundfont-fluid
      - fluidplug-git
      - fluidsynth
      - pro-audio 
      - realtime-generic-setup
    state: present
  become: true
  become_user: aur_builder

