---
- name: Enable Wezterm on Copr
  community.general.copr:
    state: enabled
    name: wezfurlong/wezterm-nightly
- name: Enable Lazygit on Copr
  community.general.copr:
    state: enabled
    name: atim/lazygit
