---
- name: Enable Wezterm on Copr
  community.general.copr:
    state: enabled
    name: wezfurlong/wezterm-nightly
- name: Enable Lazygit on Copr
  community.general.copr:
    state: enabled
    name: atim/lazygit
- name: Enable Fisher on Copr
  community.general.copr:
    state: enabled
    name: bdperkin/fisher
- name: Enable Starship on Copr
  community.general.copr:
    state: enabled
    name: ffreiheit/starship
- name: Enable iosevka on Copr
  community.general.copr:
    state: enabled
    name: peterwu/iosevka
- name: Enable firefox-developer-edition on Copr
  community.general.copr:
    state: enabled
    name: the4runner/firefox-dev
- name: Install Snapd
  package:
    name: 
      - snapd
    state: present
