---
- name: Enable Wezterm on Copr
  community.general.copr:
    state: enabled
    name: wezfurlong/wezterm-nightly
- name: Enable Lazygit on Copr
  community.general.copr:
    state: enabled
    name: atim/lazygit
- name: Enable Fisher on Copr
  community.general.copr:
    state: enabled
    name: bdperkin/fisher
- name: Enable Starship on Copr
  community.general.copr:
    state: enabled
    name: ffreiheit/starship
- name: Enable iosevka on Copr
  community.general.copr:
    state: enabled
    name: peterwu/iosevka
- name: Enable firefox-developer-edition on Copr
  community.general.copr:
    state: enabled
    name: the4runner/firefox-dev
#
# - name: Add RPM Fusion free GPG key
#   ansible.builtin.rpm_key:
#     key: "{{ rpmfusion_free_gpg_key }}"
#     state: present
#   when: ansible_distribution == 'Fedora'
#
# - name: Add RPM Fusion free
#   ansible.builtin.dnf:
#     name: "{{ rpmfusion_free_repository }}"
#     state: present
#   when: ansible_distribution == 'Fedora'
#
# - name: Add RPM Fusion non-free GPG key
#   ansible.builtin.rpm_key:
#     key: "{{ rpmfusion_nonfree_gpg_key }}"
#   state: present
#   when: ansible_distribution == 'Fedora'
#
# - name: Add RPM Fusion non-free
#   ansible.builtin.dnf:
#     name: "{{ rpmfusion_nonfree_repository }}"
#     state: present
#   when: ansible_distribution == 'Fedora'
# - name: Enable the RPM Fusion repository
#   dnf:
#     name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
#     state: present
#   when: ansible_distribution == 'Fedora'
# - name: Enable the RPM Fusion repository
#   dnf:
#     name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
#     state: present
#   when: ansible_distribution == 'Fedora'
