---
- name: Remove vim because of conflicts with Neovim-symlinks
  package:
    name:
      - vim
    state: absent

- name: Install Neovim packages
  package:
    name: 
      - neovim
      - xclip
      - nodejs
      - npm
    state: present
  become: true
